os:
  - linux

language: cpp

dist: trusty

addons: &1
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
    env:
      - CMAKE_VERSION="3.12.1"
      - CMAKE_GENERATOR="Unix Makefiles"
      - BUILDFLAGS="VERBOSE=1"

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=gcc-7 ;
      export CXX=g++-7 ;
