os:
  - linux

language: cpp

dist: trusty

addons: &1
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
    env:
      - CMAKE_VERSION="3.12.1"
      - CMAKE_GENERATOR="Unix Makefiles"
      - BUILDFLAGS="VERBOSE=1"
install:
  - ./testing/dependencies/travis/cmake.sh

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      test -n $CC && unset CC && export CC=gcc-7;
      test -n $CXX && unset CXX && export CXX=g++-7;
    fi

script:
  - cmake ..; make; ctest
